### ISSUE TITLE
Invalid shape: Hole is not within polygon

### ISSUE THREAD

**Issue by graphific** [planetlabs/notebooks#100]
Both the [crop-classification/classify-cart-l8-ps.ipynb ](https://github.com/planetlabs/notebooks/tree/master/jupyter-notebooks/crop-classification/classify-cart-l8-ps.ipynb)and [crop-classification/classify-cart.ipynb](https://github.com/planetlabs/notebooks/tree/master/jupyter-notebooks/crop-classification/classify-cart.ipynb) throw an error when trying to download the planet data in the 4th cell running` planet data download`

```activating: 0            complete: 0              elapsed: 0                    
paging: False            pending: 0                                             

activating: 0            complete: 0              elapsed: 1                    
paging: False            pending: 0                                             

Error: BadQuery: {"field": {}, "general": [{"message": "invalid_shape_exception: Invalid shape: Hole is not within polygon"}]}
```

I'm running the jupyter notebook directly from the docker container

**Comment by jreiberkyle** [comment]
Are you referring to the following command?
```
# First test if scene file exists, if not, use the Planet commandline tool to download the image, metadata, and udm.
# This command assumes a bash shell, available in Unix-based operating systems.
train_scene = train_files['scene']
!test -f $train_scene || \
    planet data download \
        --item-type PSOrthoTile \
        --dest $train_folder \
        --asset-type analytic,analytic_xml,udm \
        --string-in id $train_scene_id
```
I am unable to replicate this error and don't actually see a geospatial component to this search (which I would expect with the kind of error you describe).

**Comment by jreiberkyle** [comment]
closing for now, will reopen if communication resumes
