### ISSUE TITLE
Planet API not being accepted for quick search

### ISSUE THREAD

**Issue by Andy666lab** [planetlabs/notebooks#139]
I am learning to use Python to search and download images from Planet, according to the link, https://github.com/planetlabs/notebooks/blob/master/jupyter-notebooks/data-api-tutorials/search_and_download_quickstart.ipynb. 

When I run the In[1] tp [3] codes with Python, 
it shows 
{
 "general": [
  {
   "message": "{\"interval\": \"Rogue field\"}"
  }
 ],
 "field": {}
}
I think there is something wrong with this url in 'fire off the POST request',  'https://api.planet.com/data/v1/quick-search'. Could you please help solve the issue to let me run the correct codes? Thanks a lot!

**In[1] to [3] codes**
`# Stockton, CA bounding box (created via geojson.io) 
geojson_geometry = {
  "type": "Polygon",
  "coordinates": [
    [ 
      [-121.59290313720705, 37.93444993515032],
      [-121.27017974853516, 37.93444993515032],
      [-121.27017974853516, 38.065932950547484],
      [-121.59290313720705, 38.065932950547484],
      [-121.59290313720705, 37.93444993515032]
    ]
  ]
}

# get images that overlap with our AOI 
geometry_filter = {
  "type": "GeometryFilter",
  "field_name": "geometry",
  "config": geojson_geometry
}

# get images acquired within a date range
date_range_filter = {
  "type": "DateRangeFilter",
  "field_name": "acquired",
  "config": {
    "gte": "2016-08-31T00:00:00.000Z",
    "lte": "2016-09-01T00:00:00.000Z"
  }
}

# only get images which have <50% cloud coverage
cloud_cover_filter = {
  "type": "RangeFilter",
  "field_name": "cloud_cover",
  "config": {
    "lte": 0.5
  }
}

# combine our geo, date, cloud filters
combined_filter = {
  "type": "AndFilter",
  "config": [geometry_filter, date_range_filter, cloud_cover_filter]
}

import os
import json
import requests
from requests.auth import HTTPBasicAuth

# API Key stored as an env variable
PLANET_API_KEY = os.getenv('PL_API_KEY')

item_type = "PSScene4Band"

# API request object
search_request = {
  "interval": "day",
  "item_types": [item_type], 
  "filter": combined_filter
}

# fire off the POST request
search_result = \
  requests.post(
    'https://api.planet.com/data/v1/quick-search',
    auth=HTTPBasicAuth(PLANET_API_KEY, ''),
    json=search_request)

print(json.dumps(search_result.json(), indent=1))`

**Comment by sarasafavi** [comment]
hi @Andy666lab - thank you for raising this issue. You found a bug in the example code! The issue has been fixed: to resolve, just remove `"interval": "day"` from your request payload.

**Comment by Andy666lab** [comment]
> hi @Andy666lab - thank you for raising this issue. You found a bug in the example code! The issue has been fixed: to resolve, just remove `"interval": "day"` from your request payload.

Thanks a lot! It works.
