### ISSUE TITLE
Small bug in planet_cli_introduction.ipynb

### ISSUE THREAD

**Issue by cristi-zz** [planetlabs/notebooks#184]
In https://github.com/planetlabs/notebooks/blob/f1e02da86f2bad2da8948338de9025689ce78004/jupyter-notebooks/data-api-tutorials/planet_cli_introduction.ipynb there is a bug, 
the line

``body.await()`` 

should read

``body.wait()``

Cheers!

**Comment by mkshah605** [comment]
Thank you @cristi-zz for your note! The above link references a previous version of the notebook, which has now been updated. You can see the most recent version here: https://github.com/planetlabs/notebooks/blob/master/jupyter-notebooks/data-api-tutorials/planet_python_client_introduction.ipynb
