### ISSUE TITLE
GEE Integration

### ISSUE THREAD

**Issue by kevinlacaille** [planetlabs/notebooks#210]
Create a notebook walking a user through GEE integration with Planet data.
**Story:** This is how you order data from Planet and delivery it into GEE.
**For a blog post:** Here are a few fun operations, once in GEE (NDVI, NDWI, mosaicing tool, etc.); cool EE integration visualizations; code snippets from SDK notebook; JSON example; CLI example
**Steps:**
- Get GEE account
- Get GCS credentials
- Create cloud config JSON with GEE destination 
- Order data and have it delivered to GEE destination

**Comment by cholmes** [comment]
A one thing to note:
* For now we should recommend the use of --no-stac in the CLI, and whatever the python equivalent is, as there's a bug in Planet's GEE ingestion, which likely won't be resolved super soon. But we should plan on it being resolved and then be able to update docs in the future.

I think the core articulated here is right on, and I'd focus on getting to that end-to-end with blog post and doc update first. But if there's additional time it could be nice to expand in some different directions:

* Make a CLI tutorial - the same core JSON will be the same, the core is teaching people that JSON, but CLI people should be able to call `planet orders create` with it and then download it. I'd just put that directly in the docs, not as a notebook.
* Basemaps in orders - many users of this will be NICFI, and NICFI just has access to basemaps, so would be good to at least have one sample call that does basemaps.
* How to do 'self-ingest' - like deliver to a google cloud bucket and then register it in GEE on your own (but point people on how to register). A user I talked to on the CLI was asking about it - seems like our GEE ingestion doesn't really expose where it goes, and I'm not sure if it gets ingested or registered, etc. Some people want more control - to know they have a COG in their bucket, which they can also use in GEE.

**Comment by cholmes** [comment]
Also, it looks like GEE supports clip & harmonize - https://developers.planet.com/docs/integrations/gee/delivery/#supported-raster-operations. I'd definitely make the example using both of those operations (and mention how other operations aren't supported...).

Their docs look pretty good overall, so I think the beginning of the notebook will be referring people to how to get things set up. Once it's set up it looks to be a pretty simple call.

**Comment by kevinlacaille** [comment]
Created an [SDK ticket](https://github.com/planetlabs/planet-client-python/issues/773) for custom SA credentials support.
