### ISSUE TITLE
Sample image in ndvi_planetscope.ipynb does not exist

### ISSUE THREAD

**Issue by TimeScience** [planetlabs/notebooks#229]
From notebook: https://github.com/planetlabs/notebooks/blob/master/jupyter-notebooks/ndvi/ndvi_planetscope.ipynb:

This url gives a 404
URL = "https://api.planet.com/data/v1/item-types/PSScene/items/20160831_180302_0e26"

![image](https://user-images.githubusercontent.com/3067588/209907644-84b79f4b-9453-422a-b4be-3e10df1c54a9.png)

Code from line 33 onward returns empty values and later lines fail because the dictionary is empty...

![image](https://user-images.githubusercontent.com/3067588/209907791-d573e9e1-e510-47a3-9ad8-b4d9c1fa5197.png)
![image](https://user-images.githubusercontent.com/3067588/209907897-554bb539-4033-474b-a569-e064f045818f.png)

**Comment by mkshah605** [comment]
Thanks @TimeScience for flagging this! We've updated the code so you should be able to see the thumbnail now.

**Comment by TimeScience** [comment]
Great, thanks!
