### ISSUE TITLE
Cannot clone the repository

### ISSUE THREAD

**Issue by chetan2309** [planetlabs/notebooks#26]
I am trying to clone the git repository and running this command

[git clone git@github.com:planetlabs/notebooks.git](url)

Getting the below error. Is there anything that I am missing?

**git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.**

**Comment by sarasafavi** [comment]
@chetan2309 there was a brief period where this repo was unavailable last month, but that should be fixed now. Can you let us know if you are still having this issue today?
