### ISSUE TITLE
analytics-snippets/raster_to_vector_roads 

### ISSUE THREAD

**Issue by emma-steuer** [planetlabs/notebooks#300]
filepath problems, docs, formatting, etc

**Comment by sgillies** [comment]
@emma-steuer @mkshah605 what would you think about eliminating the "GDAL Command-Line Interface (CLI)" from this notebook? Then there would no longer be a dependency on GDAL's python bindings.

**Comment by emma-steuer** [comment]
@sgillies I think that's a great idea.
