### ISSUE TITLE
clip-api-demo JSONDecode Error

### ISSUE THREAD

**Issue by joemcglinchy** [planetlabs/notebooks#46]
Jen, I was looking at the clip-api-demo notebook with a colleague here and we were able to get it working. However, there is a short section of code which I ended up surrounding in a try-except block since I was getting a JSONDecode error which was causing Python to crash:

https://github.com/planetlabs/notebooks/blob/2760ee1b3b8d4db6f2aa61dcd2bc215911f5cb4c/jupyter-notebooks/data-api-tutorials/clip_and_ship_introduction.ipynb#L133

```
# If clipping process succeeded , we are done
        try:
            if check_state_request.json()['state'] == 'succeeded':
                clip_download_url = check_state_request.json()['_links']['results'][0]
                clip_succeeded = True
                print("Clip of scene succeeded and is ready to download") 

            # Still activating. Wait 1 second and check again.
            else:
                print("...Still waiting for clipping to complete...")
                time.sleep(1)
        except Exception as e:
            print('Exception! {}'.format(e))
            print("...Still waiting for clipping to complete...")
            time.sleep(1)
```

Just curious if you had seen that before or maybe I'm just lucky!

**Comment by jreiberkyle** [comment]
Hey @joemcglinchy - I haven't seen that exception yet. Sometimes something is up with the api service, to check you can go to [status.planet.com](status.planet.com).  I realize it been a while now, so I am going to close this, but if you get a chance to retry and the exception pops up again, let's re-open and take another look.
