### ISSUE TITLE
Make notebooks available in Docker env

### ISSUE THREAD

**Issue by robmarkcole** [planetlabs/notebooks#52]
I've successfully run the Docker container but discovered that the example notebooks are not in the env by default, so am uploading them manually. Would be good if these were available by default

**Comment by robmarkcole** [comment]
I mean, all of the notebooks in this repo

**Comment by sarasafavi** [comment]
@robmarkcole all notebooks in this repo are available via the `/tree` listing once the local Jupyter server is active (e.g., `http://localhost:8888/tree` using the default config).

Happy to look into this further if you can provide a more detailed problem description -- otherwise, closing for now.

**Comment by robmarkcole** [comment]
@sarasafavi the `tree` folder was empty, and I don't see the notebooks being added in the [DOCKERFILE](https://github.com/planetlabs/notebooks/blob/master/planet-notebook-docker/Dockerfile).  A screenshot of my folder (with uploaded files) below:

![image](https://user-images.githubusercontent.com/11855322/42922504-b6eb7064-8b18-11e8-86a0-08ad3798ea0d.png)

**Comment by robmarkcole** [comment]
@sarasafavi I had indeed omitted the `cd ..` and in my ignorance assumed I was in a folder structured within the docker container. Cheers

**Comment by rumski20** [comment]
I'm still having this same issue as described by @robmarkcole -- http://localhost:8888/tree shows up empty:
![image](https://user-images.githubusercontent.com/6474942/181280995-60c25bb9-cf50-4c71-aad7-9e51adb0a67d.png)

I'm on a windows OS and I tried running all of the variants listed here: https://github.com/planetlabs/notebooks#run-the-container
Also, I made sure that I'm at the root of the repo, when running `docker run ...`

Any help you can provide is much appreciated. I'm eager to check out these notebooks.
