### ISSUE TITLE
ndvi_planetscope requests API key

### ISSUE THREAD

**Issue by robmarkcole** [planetlabs/notebooks#54]
Running the Docker container, the notebook `ndvi_planetscope.ipynb` requests my API key at the line `!planet data download --item-type PSScene4Band --dest data --asset-type analytic,analytic_xml --string-in id 20160831_180302_0e26`. It appears that the environment variable `PL_API_KEY` is not being set correctly. I tried setting the key within the notebook using `%env PLANET_API_KEY='my_key'` but this also results in the error `Error: InvalidAPIKey: {"message": "Please enter your API key.", "errors": []}`

The following was successful `!planet --api-key my_key data download --item-type PSScene4Band --dest data --asset-type analytic,analytic_xml --string-in id 20160831_180302_0e26 `

Note you also don't set `%matplotlib inline` in this notebook

**Comment by sarasafavi** [comment]
@robmarkcole please double-check the API key you passed into the container via `docker run`. 

From any Notebook, you can do this by adding a codeblock and running:
```
import os
print(os.getenv("PL_API_KEY"))
```

If the value printed is anything other than the string `'12345'`, where 12345 is your API key, then you need to re-run `docker run` with the correct API key.

*NOTE:* your output value may be e.g., `'[12345]'` -- that's a common mis-reading of our README instructions. Please note that the square brackets are _not_ part of the API key to pass in!

> Note you also don't set %matplotlib inline in this notebook

This Notebook uses `plt.show()` to trigger inline figure displays, and likewise `%matplotlib inline` is not necessary:

![image](https://user-images.githubusercontent.com/1209376/42949662-e223e530-8b37-11e8-83d2-52db3aba9989.png)

**Comment by robmarkcole** [comment]
@sarasafavi I was indeed using the `[ ]`

**Comment by tarnetintern** [comment]
> @sarasafavi I was indeed using the `[ ]`
> 
> Re the `%matplotlib inline`, the first time I run the cell no plot is displayed, I just see:
> 
> ![image](https://user-images.githubusercontent.com/11855322/42984146-0422ff12-8be3-11e8-90f2-9bf39e277f6d.png)
> 
> This is why I concluded `%matplotlib inline` is required. However on running the cell a second time, the plot is displayed..!

U need use jupyter notebook. I see you using another kernel
