### ISSUE TITLE
Current issue with docker build - gdal version

### ISSUE THREAD

**Issue by rmuellerjr** [planetlabs/notebooks#60]
I was following the directions from the previous page, building the Docker image and ran into an issue at step 3/24 (install GDAL step). Looks like something might have changed with the gdal version (2.1.3) from the expected channel.

![image](https://user-images.githubusercontent.com/8677397/45838317-6f8c6180-bcdf-11e8-9c67-1acaca90c2b1.png)

**Comment by rmuellerjr** [comment]
Note - I made the changes suggested by theTechie on 8/16 (
https://github.com/planetlabs/notebooks/pull/56), which satisfies the GDAL requirement. I'll do some testing to see if there any issues with the updated GDAL version.

**Comment by jreiberkyle** [comment]
@rmuellerjr I found the fix in #56 to work for my gdal install. Is this still an issue for you? I just did some work on the Dockerfile, simplifying it and it's been working great for me. In regard to gdal, it pretty much just implements what is in #56. However, if you want to start from there, you can access that version of the Dockerfile [here](https://github.com/planetlabs/notebooks/blob/52bce7f7fd925d1bf8d1899e2da56f30bca0dce4/planet-notebook-docker/Dockerfile).

**Comment by jreiberkyle** [comment]
Actually, that PR was merged so you can just pull the master branch and rebuild.

**Comment by rmuellerjr** [comment]
Great, thanks! I need to try this again. I had some issues opening the Jupyter notenbook on localhost with the token and never returned. I will try again here.
