### ISSUE TITLE
localhost refused to connect

### ISSUE THREAD

**Issue by craigdsouza** [planetlabs/notebooks#65]
All steps in the installation process until and including 'Build the docker image' were successful. However I'm now running into this issue at the 'run the container' step.

Ran the following command in command prompt
`docker run -it --rm -v "//c/Users/Craig D/Code/planet/notebooks/jupyter-notebooks:/home/jovyan/work" -e PL_API_KEY='[MY-API-KEY]' planet-notebooks`
did not include the -p 8888:8888 flag mentioned in the README because it was already set when I ran the `docker run` command originally and running the command again while specifying -p gives the error 'port already allocated'

the snapshot below is what I get .. 
![image](https://user-images.githubusercontent.com/11412924/47782929-6f907000-dd27-11e8-8bf5-e45886f3d6ad.png)
once I open the localhost URL the page simply says 'site can't be reached - localhost refused to connect' instead of the jupyter lab notebooks I expect to see.

my system is Windows 10 and Docker version is Docker Toolbox, Docker version 18.03.0-ce, build 0520e24302

**Comment by craigdsouza** [comment]
after browsing around I realized I have to substitute _localhost_ in the URL with 192.168.99.100 and it works.. not quite sure why though

**Comment by jreiberkyle** [comment]
There is a way to configure the VM in virtualbox to set the IP of the VM as localhost. I found it with a google search a while back when I ran into the same thing.

**Comment by craigdsouza** [comment]
Thanks for the tip!
