### ISSUE TITLE
Create our own base docker image

### ISSUE THREAD

**Issue by sarasafavi** [planetlabs/notebooks#74]
In order to avoid upstream issues like #73, we should push our own base image to dockerhub.

**Comment by strixcuriosus** [comment]
It would be nice to have a CI pipeline to build, tag, and push said image.

**Comment by strixcuriosus** [comment]
Another docker build failure: https://github.com/planetlabs/notebooks/issues/84

**Comment by jreiberkyle** [comment]
Oops! I resolved this in #114.
