### ISSUE TITLE
Quick search is not working

### ISSUE THREAD

**Issue by Mishel1992** [planetlabs/notebooks#99]
Hi Everyone:
I had an issue recently trying to follow step-by-step procedure from API Introduction (tutorials)
I can't go further Quick Search section, because my API_KEY is apparently not working.
I got this answer:

{
  "message": "Please enter your API key, or email and password.",
  "errors": []
}
Everything was good for previous sections, but from here (the most important i consider) the code reboots me with that message.

Sorry if my question is too basic, but I tried looking for the answer from another blogs, trying their solutions and without success.
Thanks in advance for your reply!
Mishel.

**Comment by jreiberkyle** [comment]
Hey Mishel, could you let me know what notebook you are working with? Also, it would be helpful if you can document here exactly the command you are trying to use.

**Comment by jreiberkyle** [comment]
closing since I haven't heard back for a while. Feel free to add a comment and we can reopen
